micronaut:
  application:
    name: newsletter
---
micronaut:
  server:
    cors:
      enabled: true
---
flyway:
  datasources:
    default:
      enabled: true
---
micronaut:
  security:
    redirect:
      forbidden:
        url: '/forbidden'
      unauthorized:
        url: '/unauthorized'
    authentication: idtoken
    endpoints:
      logout:
        get-allowed: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne #TODO Set this via environment variable
---
micronaut:
  security:
    views-model-decorator:
      security-key: authentication